# Generated by Django 4.2.8 on 2024-05-22 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lounges', '0002_lounge_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoungeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked_users', models.ManyToManyField(related_name='liked_lounge_articles', to=settings.AUTH_USER_MODEL)),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lounges.lounge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_lounge_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
