# Generated by Django 4.2.8 on 2024-05-22 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lounges', '0003_loungearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoungeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked_users', models.ManyToManyField(related_name='liked_lounge_comments', to=settings.AUTH_USER_MODEL)),
                ('lounge_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lounges.loungearticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_lounge_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
