# Generated by Django 4.2.8 on 2024-05-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like_users',
            new_name='liked_users',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='like_users',
            new_name='liked_users',
        ),
    ]
