# Generated by Django 4.2.8 on 2024-05-20 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_lounge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rank',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
