# Generated by Django 4.2.8 on 2024-05-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='lounge',
        ),
    ]
