# Generated by Django 4.2.8 on 2024-05-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
