# Generated by Django 4.2.8 on 2024-05-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_trailer_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='like_users',
            new_name='liked_users',
        ),
    ]
