# Generated by Django 4.2.8 on 2024-05-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_overview_alter_movie_trailer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
