# Generated by Django 4.2.8 on 2024-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_genre_genre_id_alter_movie_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_adult',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
