# Generated by Django 4.2.8 on 2024-05-20 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_is_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortreview',
            name='rank',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
