# Generated by Django 4.2.8 on 2024-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_shortreview_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortreview',
            name='is_spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
